/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro;

import javax.swing.JCheckBox;

/**
 *
 * @author ADMIN
 */
public class addwait extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(addwait.class.getName());

    /**
     * Creates new form addwait
     */
    public addwait() {
         initComponents();
    setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    setResizable(false);

    // Limit phone number input to 10 digits
    jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyTyped(java.awt.event.KeyEvent evt) {
            char c = evt.getKeyChar();
            if (!Character.isDigit(c) || jTextField4.getText().length() >= 10) {
                evt.consume(); // ignore input
            }
        }
    }); // <-- Close the KeyAdapter here

    // Calculate age automatically when date is selected
    jDateChooser1.addPropertyChangeListener("date", evt -> {
        java.util.Date selectedDate = jDateChooser1.getDate();
        if (selectedDate != null) {
            java.util.Calendar cal = java.util.Calendar.getInstance();
            cal.setTime(selectedDate);
            int year = cal.get(java.util.Calendar.YEAR);

            int currentYear = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
            int calculatedAge = currentYear - year;

            jSpinner2.setValue(calculatedAge); // show calculated age
        } else {
            jSpinner2.setValue(0); // reset if no date selected
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSpinner2 = new javax.swing.JSpinner();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 120)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Waiter Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username:-");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age:-");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender:-");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 45)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:-");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 1, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Full Name:-");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 310, 240, 30));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 400, 240, 30));
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 100, 30));

        jTextField2.addActionListener(this::jTextField2ActionPerformed);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 240, 30));

        btn1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Script MT Bold", 1, 35)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Male");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, -1, -1));

        btn1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Script MT Bold", 1, 35)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Female");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Variable", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("submit");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 550, 130, 50));

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 1, 40)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address:-");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 240, 100));

        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 1, 40)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date of Birth:-");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Baskerville Old Face", 1, 40)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone Number:-");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, -1, -1));

        jTextField4.addActionListener(this::jTextField4ActionPerformed);
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 240, 30));

        jButton2.setBackground(java.awt.Color.red);
        jButton2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 20, 70, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 240, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro/5.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                                                                       
    // ✅ Trim input values
    String phone = jTextField4.getText().trim();
    String name = jTextField2.getText().trim();
    String username = jTextField1.getText().trim();
    String password = new String(jPasswordField1.getPassword()).trim();
    int age = (int) jSpinner2.getValue();
    String address = jTextArea1.getText().trim();
    
    // ✅ Get date from DateChooser
    java.util.Date selectedDate = jDateChooser1.getDate();
    if (selectedDate == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select date of birth");
        return;
    }

    // --- AGE CALCULATION ---
    java.util.Calendar cal = java.util.Calendar.getInstance();
    cal.setTime(selectedDate);
    int year = cal.get(java.util.Calendar.YEAR);
    int currentYear = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
    age = currentYear - year;
    jSpinner2.setValue(age); // show calculated age
    // --- AGE CALCULATION END ---

    // Format DOB for database
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
    String dob = sdf.format(selectedDate);

    // ✅ Get gender
    String gender = "";
    if (jRadioButton1.isSelected()) gender = "Male";
    else if (jRadioButton2.isSelected()) gender = "Female";
   

    // ✅ VALIDATION
    if (name.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter full name");
        return;
    }
    if (username.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter username");
        return;
    }
    if (password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter password");
        return;
    }
    if (phone.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter phone number");
        return;
    }
    if (!phone.matches("\\d{10}")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Phone number must be exactly 10 digits");
        return;
    }
    if (address.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter address");
        return;
    }
    if (gender.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select gender");
        return;
    }
    if (age <= 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid age");
        return;
    }

    // ✅ INSERT INTO DATABASE
    try {
        java.sql.Connection con = DBConnection.getConnection();
        String sql = "INSERT INTO waiter(phone,name,dob,username,password,age,address,gender) VALUES (?,?,?,?,?,?,?,?)";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, phone);
        pst.setString(2, name);
        pst.setString(3, dob);
        pst.setString(4, username);
        pst.setString(5, password);
        pst.setInt(6, age);
        pst.setString(7, address);
        pst.setString(8, gender);

        pst.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(this, "✅ Waiter Added Successfully");

        // ✅ CLEAR FORM AFTER SUCCESS
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField4.setText("");
        jPasswordField1.setText("");
        jTextArea1.setText("");
        btn1.clearSelection();
        jSpinner2.setValue(0);
        jDateChooser1.setDate(null);

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error adding waiter. Check console.");
    }

       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
adminsec a = new adminsec();
    a.setVisible(true);

    this.dispose(); 
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new addwait().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
