/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
/**
 *
 * @author ADMIN
 */
public class DeleteWaiter extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeleteWaiter.class.getName());

    /**
     * Creates new form DeleteWaiter
     */
 public DeleteWaiter() {
    initComponents();
    loadTable(); // load data when JFrame opens
}
private void loadTable() {
 
    try {
        Connection con = DBConnection.getConnection();
        String sql = "SELECT id, name, phone, dob, username, password, age, address, gender FROM waiter";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        String[] columns = {
            "Waiter ID", "Full Name", "Phone Number", "Date of Birth",
            "Username", "Password", "Age", "Address", "Gender"
        };

        DefaultTableModel model = new DefaultTableModel(columns, 0);
        jTableWaiters.setModel(model);

        while (rs.next()) {
            Object[] row = {
                rs.getInt("id"),          // ✅ FIXED
                rs.getString("name"),    // ✅ FIXED
                rs.getString("phone"),   // ✅ FIXED
                rs.getString("dob"),     // ✅ FIXED
                rs.getString("username"),
                rs.getString("password"),
                rs.getInt("age"),
                rs.getString("address"),
                rs.getString("gender")
            };
            model.addRow(row);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableWaiters = new javax.swing.JTable();
        jButtonDelete = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableWaiters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableWaiters);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 1100, 190));

        jButtonDelete.setBackground(new java.awt.Color(102, 0, 0));
        jButtonDelete.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Delete Selected Waiter");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);
        getContentPane().add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 580, -1, 60));

        jButtonBack.setBackground(java.awt.Color.red);
        jButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("X");
        jButtonBack.addActionListener(this::jButtonBackActionPerformed);
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 30, 70, -1));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delete Waiter Account");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 990, 110));

        jLabel2.setFont(new java.awt.Font("Serif", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select a waiter from the list below to delete their account.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro/11.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
       int selectedRow = jTableWaiters.getSelectedRow();
    if (selectedRow >= 0) {
        int id = (int) jTableWaiters.getValueAt(selectedRow, 0); // get waiter ID

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this waiter?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Connection con = DBConnection.getConnection();
                String sql = "DELETE FROM waiter WHERE id=?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setInt(1, id);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Waiter deleted successfully!");
                loadTable(); // refresh table after deletion

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    } else {
        JOptionPane.showMessageDialog(this, "Please select a waiter to delete.");
    } // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
adminsec a = new adminsec();
    a.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> new DeleteWaiter().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableWaiters;
    // End of variables declaration//GEN-END:variables
}
