/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package pro;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 *
 * @author ADMIN
 */
public class menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menu.class.getName());
private String imagePath = "";
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
         setResizable(false);
         
         jLabel6.setText("No Image Selected");
jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.WHITE));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Item Name:-");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Price :-");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Select Category:-");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 290, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 290, 30));

        jComboBox1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Choose Category --", "Beverages", "Starters", "Main Course", "Desserts" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 290, 50));

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton1.setText("Add Item");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 580, 170, 50));

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 170, 50));

        jButton3.setBackground(java.awt.Color.red);
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("X");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 30, 60, -1));

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 1, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No Image Selected ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 350, -1, -1));

        jButton4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton4.setText("Upload Image");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, 210, 40));

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 1, 40)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Upload Image:-");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 204, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro/13.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   String itemName = jTextField1.getText().trim();
    String priceText = jTextField2.getText().trim();
    String category = (String) jComboBox1.getSelectedItem();

    // ✅ VALIDATION
    if (itemName.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "⚠ Please enter item name");
        return;
    }
if (imagePath.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "⚠ Please upload image");
    return;
}
    if (priceText.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "⚠ Please enter price");
        return;
    }

    double price = 0;
    try {
        price = Double.parseDouble(priceText);
        if (price <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "⚠ Price must be greater than 0");
            return;
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "⚠ Enter valid numeric price");
        return;
    }

    if (category == null || category.contains("Choose")) {
        javax.swing.JOptionPane.showMessageDialog(this, "⚠ Please select category");
        return;
    }

    if (imagePath.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "⚠ Please upload image");
        return;
    }

    // ✅ DATABASE INSERT
    try (Connection con = DBConnection.getConnection()) {

        String sql = "INSERT INTO menu_items (item_name, price, category, image_path) VALUES (?, ?, ?, ?)";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, itemName);
        pst.setDouble(2, price);
        pst.setString(3, category);
        pst.setString(4, imagePath); // ✅ SAVE IMAGE PATH

        int rows = pst.executeUpdate();

        if (rows > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "✅ Item added successfully!");

            // ✅ CLEAR FORM
            jTextField1.setText("");
            jTextField2.setText("");
            jComboBox1.setSelectedIndex(0);
            jLabel6.setIcon(null);
            jLabel6.setText("No Image Selected");
            imagePath = "";
        }

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "❌ Error adding item");
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  jTextField1.setText("");
    jTextField2.setText("");
    jComboBox1.setSelectedIndex(0);
    jTextField1.setText("");
jTextField2.setText("");
jComboBox1.setSelectedIndex(0);

jLabel6.setIcon(null);
jLabel6.setText("No Image Selected");

imagePath = "";

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  this.dispose(); // closes current window
     new waitsec().setVisible(true); // if you have a main menu page

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
    int result = chooser.showOpenDialog(this);

    if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File file = chooser.getSelectedFile();

        try {
            // Create images folder if not exists
            java.io.File dir = new java.io.File("images");
            if (!dir.exists()) {
                dir.mkdir();
            }

            // Save relative path
            imagePath = "images/" + file.getName();

            // Copy file
            java.nio.file.Files.copy(
                file.toPath(),
                new java.io.File(imagePath).toPath(),
                java.nio.file.StandardCopyOption.REPLACE_EXISTING
            );

            // Show preview
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(file.getAbsolutePath());
            java.awt.Image img = icon.getImage().getScaledInstance(300, 250, java.awt.Image.SCALE_SMOOTH);

            jLabel6.setIcon(new javax.swing.ImageIcon(img));
            jLabel6.setText("");

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading image");
        }
    }// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
