/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author ADMIN
 */
public class upitem extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(upitem.class.getName());
private String imagePath = "";
    /**
     * Creates new form upitem
     */
    public upitem() {
         initComponents();   // MUST be first

    setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    setResizable(false);

    loadItemNames();
    loadCategories();

    // Allow only numbers in price field
    jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            char c = evt.getKeyChar();
            if (!Character.isDigit(c) && c != '.') {
                evt.consume();
            }
        }
    });
    }
    private void loadCategories() {
    jComboBox2.removeAllItems();
    jComboBox2.addItem("Select Category"); 

    try (Connection con = DBConnection.getConnection()) {
        String sql = "SELECT DISTINCT category FROM menu_items";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            jComboBox2.addItem(rs.getString("category"));
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading categories: " + e.getMessage());
    }
}

private void loadItemNames() {
    jComboBox1.removeAllItems();  

    try (Connection con = DBConnection.getConnection()) {
        String sql = "SELECT item_name FROM menu_items";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            jComboBox1.addItem(rs.getString("item_name"));
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading items: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 240, 30));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Item:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Price:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Category:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(this::jComboBox2ActionPerformed);
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 240, 40));

        jTextField1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 240, 30));

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton1.setText("Update Item");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 620, 150, 50));

        jButton2.setBackground(java.awt.Color.red);
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 30, 60, -1));

        jButton3.setBackground(new java.awt.Color(102, 0, 0));
        jButton3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear Fields");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 150, 50));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 100)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Update Menu Item Details");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No Image Selected");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 350, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jButton4.setText("Update Img");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 160, 40));

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 1, 40)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("New Image:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Downloads\\cafe\\12.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
   String selectedItem = (String) jComboBox1.getSelectedItem();

    if (selectedItem != null) {
        try (Connection con = DBConnection.getConnection()) {

            String sql = "SELECT * FROM menu_items WHERE item_name=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, selectedItem);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {

                // ✅ GET DATA
                String price = rs.getString("price");
                String category = rs.getString("category");
                String imgPath = rs.getString("image_path");

                // ✅ SET PRICE
                jTextField1.setText(price);

                // ✅ LOAD CATEGORY PROPERLY
                loadCategories();
                jComboBox2.setSelectedItem(category);

                // ✅ SHOW IMAGE
                if (imgPath != null && !imgPath.isEmpty()) {

                    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgPath);
                    java.awt.Image img = icon.getImage().getScaledInstance(300, 250, java.awt.Image.SCALE_SMOOTH);

                    jLabel6.setIcon(new javax.swing.ImageIcon(img));
                    jLabel6.setText("");

                    // store current image path
                    imagePath = imgPath;

                } else {
                    jLabel6.setIcon(null);
                    jLabel6.setText("No Image");
                    imagePath = "";
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String selectedItem = (String) jComboBox1.getSelectedItem();
    String newPrice = jTextField1.getText().trim();
    String newCategory = (String) jComboBox2.getSelectedItem();

    // ✅ VALIDATION
    if (selectedItem == null || selectedItem.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select item");
        return;
    }

    if (newPrice.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Enter price");
        return;
    }
if (newCategory == null || newCategory.equals("Select Category")) {
    javax.swing.JOptionPane.showMessageDialog(this, "Select category");
    return;
}
    double priceValue;
    try {
        priceValue = Double.parseDouble(newPrice);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid price");
        return;
    }

    // ✅ DATABASE UPDATE (INCLUDING IMAGE)
    try (Connection con = DBConnection.getConnection()) {

        String sql = "UPDATE menu_items SET price=?, category=?, image_path=? WHERE item_name=?";
        PreparedStatement pst = con.prepareStatement(sql);

        pst.setDouble(1, priceValue);
        pst.setString(2, newCategory);
        pst.setString(3, imagePath); // ✅ image update
        pst.setString(4, selectedItem);

        int rows = pst.executeUpdate();

        if (rows > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "✅ Updated Successfully!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "❌ Update Failed");
        }

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   jTextField1.setText("");
    jComboBox2.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose(); // close current window
     new waitsec().setVisible(true); // if you want to go back to menu page
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
    chooser.showOpenDialog(this);

    java.io.File file = chooser.getSelectedFile();

    if (file != null) {
        try {
            // Save in images folder
            imagePath = "images/" + file.getName();

            java.nio.file.Files.copy(
                file.toPath(),
                new java.io.File(imagePath).toPath(),
                java.nio.file.StandardCopyOption.REPLACE_EXISTING
            );

            // Show preview
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(file.getAbsolutePath());
            java.awt.Image img = icon.getImage().getScaledInstance(200, 150, java.awt.Image.SCALE_SMOOTH);

            jLabel6.setIcon(new javax.swing.ImageIcon(img));
            jLabel6.setText("");

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading image");
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new upitem().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
